# name | ssh target (alias from ~/.ssh/config or user@host) | port
sherlock        | sherlock                | 22
aak-first       | aak-first               | 22
aak-second      | aak-second              | 22
aak-third       | aak-third               | 22
aak-llm         | aak-llm                 | 22
sedan           | sedan                   | 22
gpu1.sedan.pro  | gpu1.sedan.pro          | 22
gpu2.sedan.pro  | gpu2.sedan.pro          | 22
gpu3.sedan.pro  | gpu3.sedan.pro          | 22
digitalocean    | root@207.154.216.100    | 22
regru_msk       | regru_msk               | 22
horek_fi        | root@2.27.33.175        | 22
horek_ge        | root@2.26.22.251        | 22
horek_ge2       | root@193.233.85.181     | 22
qwins_ge        | root@84.21.189.74       | 22
